services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail: # Agente para enviar logs a Loki
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log # O el path de logs de tus contenedores
      - ./promtail-local-config.yml:/etc/promtail/config.yml
      - ./ej1/app.log:/app/app.log
    command: -config.file=/etc/promtail/config.yml
  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:12.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes: # Para persistir dashboards y datasources
      - grafana-data:/var/lib/grafana
  # ... (otros servicios)
  tempo:
    image: grafana/tempo:2.7.2
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml # Configuración básica de Tempo
    ports:
      - "3200:3200" # Tempo UI & API
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      # - "14268:14268" # Jaeger HTTP (si se usa)

volumes:
  grafana-data: