server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory

query_frontend:
  max_outstanding_per_tenant: 1024

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces